version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  # dynamodb:
  #   command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
  #   image: "amazon/dynamodb-local:latest"
  #   container_name: dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./dynamodbdata:/home/dynamodblocal/data"
  #   working_dir: /home/dynamodblocal