# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "pg"
gem "activerecord"
gem "aws-sdk-lambda"
gem "platform", path: "../platform"
